ports:
  - port: 2181
    onOpen: ignore
  - port: 2888
    onOpen: ignore
  - port: 3888
    onOpen: ignore
  - port: 4317
    onOpen: ignore
  - port: 4318
    onOpen: ignore
  - port: 8123
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9181
    onOpen: ignore
  - port: 35527
    onOpen: ignore

tasks:
  - name: SigNoz
    init: |
      cd /workspace
      git clone https://github.com/SigNoz/signoz.git
      cd /workspace/signoz/deploy/docker/clickhouse-setup
      sed -i '/hotrod/,$d' docker-compose.yaml
      docker compose pull
    command:
      docker compose up -d
  - name: Jam Tools
    init: |
      npm install
      npm install -g turbo
      turbo run build
    command: |
      npm run dev
