packages:
  - "apps/jamtools"
  - "packages/jamtools/core"
  - "packages/jamtools/features"
  - "packages/springboard/platforms/node"
  - "packages/springboard/platforms/tauri"
  - "packages/springboard/platforms/webapp"
  - "packages/springboard/platforms/partykit"
  - "packages/springboard/platforms/react-native"
  - "packages/springboard/*"
  - "packages/springboard/external/*"
  - "packages/*"
  - "configs"
catalog:
  react: "^19.1.0"
  react-dom: "^19.1.0"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.0"
