packages:
  - "apps/jamtools"
  - "apps/small_apps"
  - "packages/jamtools/core"
  - "packages/jamtools/features"
  - "packages/springboard/platforms/node"
  - "packages/springboard/platforms/tauri"
  - "packages/springboard/platforms/webapp"
  - "packages/springboard/platforms/partykit"
  - "packages/springboard/platforms/react-native"
  - "packages/springboard/plugins/*"
  - "packages/jamtools/mitosis-components/library"
  - "packages/springboard/*"
  - "packages/springboard/external/*"
  - "packages/*"
  - "configs"
catalog:
  react: "^19.1.0"
  react-dom: "^19.1.0"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.0"
  rxjs: "^7.0.0"
  immer: "^10.1.1"
  json-rpc-2.0: "^1.7.0"
  reconnecting-websocket: "^4.4.0"
  commander: "^12.1.0"
  tslib: "^2.8.1"
  "@types/node": "^20.14.2"
  hono: "^4.6.7"
  "@trpc/server": "^10.45.2"
  "@trpc/client": "^10.45.2"
  zod: "^3.23.8"
  "@hono/trpc-server": "^0.3.2"
  "react-router-dom": "^6.28.1"
  esbuild: "^0.25.0"
  estree-walker: "^2"
