name = "jamtools-springboard"
main = "src/entrypoints/cloudflare_worker_entrypoint.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "jamtools-springboard-prod"

# partyserver configuration
[durable_objects]
bindings = [
  { name = "parties", class_name = "SpringboardRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["SpringboardRoom"]

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"