site_name: Jam Tools
docs_dir: content
theme:
  name: material
  features:
    - navigation.expand


extra_css:
  - stylesheets/custom.css

nav:
  - Home: ./typedoc_docs/README.md
  - Developer Documentation:
    - Module API: ./typedoc_docs/module_api/classes/ModuleAPI.md
    - States API: ./typedoc_docs/module_api/classes/StatesAPI.md
