site_name: Springboard
docs_dir: content
theme:
  name: material
  highlightjs: true
  palette:
    scheme: slate
  #   primary: indigo
  features:
    - navigation.expand
    - navigation.footer
markdown_extensions:
    - pymdownx.highlight
    #   anchor_linenums: true
    #   line_spans: __span
    #   pygments_lang_class: true
    # - pymdownx.inlinehilite
    # - pymdownx.snippets
    - pymdownx.superfences

extra_css:
  - stylesheets/custom.css

nav:
  - Home: ./index.md
  - Springboard:
    - Overview: ./springboard/overview.md
    - Developing a module: ./springboard/module-development.md
    - Deployment Contexts:
      - Single/Multi-player: ./springboard/deployment-contexts/deployment-contexts.md
      - Desktop App: ./springboard/deployment-contexts/desktop-app.md
      - Mobile App: ./springboard/deployment-contexts/mobile-app.md
    - API reference:
      - Module API: ./typedoc_docs/module_api/classes/ModuleAPI.md
      - States API: ./typedoc_docs/module_api/classes/StatesAPI.md

  - Jam Tools:
    - Overview: ./jamtools/overview.md
    - Modules:
      - Macro module: ./jamtools/macro-module.md
      - MIDI IO module: ./jamtools/midi-io-module.md

plugins:
  - search
  - include-markdown
