name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy to production on push to main
  pull_request:
    branches:
      - main  # Deploy a preview on pull requests to main

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs and Material theme
      run: |
        pip install mkdocs mkdocs-material

    - name: Build and Deploy for Production
      if: github.ref == 'refs/heads/main'
      run: mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Deploy for PR Preview
      if: github.event_name == 'pull_request'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        mkdocs gh-deploy --remote-branch gh-pages-preview-${PR_NUMBER} --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
